# Generated by Django 4.0.5 on 2022-06-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbers',
            name='phone_content',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
