# Generated by Django 4.0.5 on 2022-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_page', '0003_alter_patientdiagnostic_diagnostic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
